import Footer from "@/src/components/Footer";
import Header from "@/src/components/Header";
import { HeaderVisibilityProvider } from "@/src/components/HeaderVisibility";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Grain & Grains",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <HeaderVisibilityProvider>
      <Header />
      {children}
      <Footer />
    </HeaderVisibilityProvider>
  );
}
